replicaCount: 1

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabled: false
  tls:
    enabled: false

tls:
  enabled: false
  certs:
    ca:
      enabled: false
    broker:
      enabled: false
    client:
      enabled: false
    controller:
      enabled: false
    external:
      enabled: false

#expose kafka ports
ports:
  client:
    enabled: true
    port: 9092
  controller:
    enabled: true
    port: 9093
  interbroker:
    enabled: true
    port: 9094
  external:
    enabled: true
    port: 9095
    servicePort: 9095

externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  controller:
    service:
      type: NodePort
      nodePorts[0]: '9095'
      domain: localhost

rbac:
  create: true

broker:
  automountServiceAccountToken: true

controller:
  automountServiceAccountToken: true

defaultInitContainers:
  autoDiscovery:
    enabled: true

nodeport:
  enabled: true

extraEnvVars:
- name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
  value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
- name: KAFKA_CFG_LISTENERS
  value: "CLIENT://:9092,CONTROLLER://:9093,INTERNAL://:9094,EXTERNAL://:9095"
- name: KAFKA_CFG_ADVERTISED_LISTENERS
  value: "INTERNAL://$(MY_POD_NAME).kafka-headless.$(MY_POD_NAMESPACE).svc.cluster.local:9094,CLIENT://$(MY_POD_NAME).kafka-headless.$(MY_POD_NAMESPACE).svc.cluster.local:9092,EXTERNAL://$(MY_POD_NAME).kafka-headless.$(MY_POD_NAMESPACE).svc.cluster.local:9095"
# enable auto create topics
# - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
#  value: "true"
- name: KAFKA_CFG_AUTO_CREATE_TOPICS
  value: "locations:1:1"
