apiVersion: apps/v1
kind: Deployment
metadata:
  name: locations-consumer-kafka2db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locations-consumer-kafka2db
  template:
    metadata:
      labels:
        app: locations-consumer-kafka2db
    spec:
      containers:
      - name: locations-consumer-kafka2db
        image: winfriedbreuer/udaconnect-locations-consumer-kafka2db:latest
        imagePullPolicy: "Always"
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC
