apiVersion: apps/v1
kind: Deployment
metadata:
  name: udaconnect-kafka-locations-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-kafka-locations-consumer
  template:
    metadata:
      labels:
        app: udaconnect-kafka-locations-consumer
    spec:
      containers:
      - name: udaconnect-kafka-locations-consumer
        image: winfriedbreuer/udaconnect-kafka-locations-consumer:latest
        imagePullPolicy: "Always"
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC
        - name: LOCATIONS_SERVICE_ENDPOINT
          # This is the URL of the udaconnect-locations-api service
          # in the udaconnect namespace. It is used to send location data.
          value: "http://udaconnect-locations-api.default.svc.cluster.local:5000/api/locations"
